name:                hs-tl-types
version:             0.1.0.0
github:              "ablearthy/hs-tl-types"
license:             BSD3
author:              "Able Arthy"
maintainer:          "ablearthy@gmail.com"
copyright:           "2022 Able Arthy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ablearthy/hs-tl-types#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text

library:
  source-dirs: src

executables:
  hs-tl-types-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - hs-tl-types

tests:
  hs-tl-types-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-tl-types


